//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `APIConfig.plist`.
    static let apiConfigPlist = Rswift.FileResource(bundle: R.hostingBundle, name: "APIConfig", pathExtension: "plist")

    /// `bundle.url(forResource: "APIConfig", withExtension: "plist")`
    static func apiConfigPlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.apiConfigPlist
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 1 images.
  struct image {
    /// Image `FoodGuru`.
    static let foodGuru = Rswift.ImageResource(bundle: R.hostingBundle, name: "FoodGuru")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "FoodGuru", bundle: ..., traitCollection: ...)`
    static func foodGuru(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.foodGuru, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 5 localization keys.
    struct localizable {
      /// en translation: Decode error
      ///
      /// Locales: en, bg-BG
      static let api_error_decode = Rswift.StringResource(key: "api_error_decode", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "bg-BG"], comment: nil)
      /// en translation: Get started
      ///
      /// Locales: en, bg-BG
      static let landing_screen_get_started_button_title = Rswift.StringResource(key: "landing_screen_get_started_button_title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "bg-BG"], comment: nil)
      /// en translation: Session expired
      ///
      /// Locales: en, bg-BG
      static let api_error_unauthorized = Rswift.StringResource(key: "api_error_unauthorized", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "bg-BG"], comment: nil)
      /// en translation: Unknown error
      ///
      /// Locales: en, bg-BG
      static let api_error_unknown = Rswift.StringResource(key: "api_error_unknown", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "bg-BG"], comment: nil)
      /// en translation: Welcome to FoodGuru your best friend when you are hungry
      ///
      /// Locales: en, bg-BG
      static let landing_screen_title = Rswift.StringResource(key: "landing_screen_title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "bg-BG"], comment: nil)

      /// en translation: Decode error
      ///
      /// Locales: en, bg-BG
      static func api_error_decode(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("api_error_decode", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "api_error_decode"
        }

        return NSLocalizedString("api_error_decode", bundle: bundle, comment: "")
      }

      /// en translation: Get started
      ///
      /// Locales: en, bg-BG
      static func landing_screen_get_started_button_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("landing_screen_get_started_button_title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "landing_screen_get_started_button_title"
        }

        return NSLocalizedString("landing_screen_get_started_button_title", bundle: bundle, comment: "")
      }

      /// en translation: Session expired
      ///
      /// Locales: en, bg-BG
      static func api_error_unauthorized(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("api_error_unauthorized", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "api_error_unauthorized"
        }

        return NSLocalizedString("api_error_unauthorized", bundle: bundle, comment: "")
      }

      /// en translation: Unknown error
      ///
      /// Locales: en, bg-BG
      static func api_error_unknown(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("api_error_unknown", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "api_error_unknown"
        }

        return NSLocalizedString("api_error_unknown", bundle: bundle, comment: "")
      }

      /// en translation: Welcome to FoodGuru your best friend when you are hungry
      ///
      /// Locales: en, bg-BG
      static func landing_screen_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("landing_screen_title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "landing_screen_title"
        }

        return NSLocalizedString("landing_screen_title", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      // There are no resources to validate
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R {
  fileprivate init() {}
}
